name: file_storage_firebase
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_storage: ^11.0.10

  shared_kernel:
    path: ../shared_kernel

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.21.0
  flutter_lints: ^2.0.0

  firebase_storage_mocks: ^0.6.0+1
