name: products_manager
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  equatable: ^2.0.5
  uuid: ^3.0.7

  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1

  domain_models:
    path: ../domain_models

  file_helpers:
    path: ../file_helpers

  data_storage_repository:
    path: ../data_storage_repository

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
