name: products_catalog
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  shared_kernel:
    path: ../../shared_kernel

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
