name: products_catalog
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10

  shared_kernel:
    path: ../../shared_kernel

  image_processor:
    path: ../../image_processor

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
