// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6J4OQ85fu1OU00_DYGB6b6kwuZcMBaLU',
    appId: '1:586341334501:web:cd4ff1e56728731651c30c',
    messagingSenderId: '586341334501',
    projectId: 'inventory-b52ef',
    authDomain: 'inventory-b52ef.firebaseapp.com',
    storageBucket: 'inventory-b52ef.appspot.com',
    measurementId: 'G-DLXJDGRQY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdSynHFy5CfZBGQXHdSuWgWufoKUndr1Y',
    appId: '1:586341334501:android:49cf132c5209d00a51c30c',
    messagingSenderId: '586341334501',
    projectId: 'inventory-b52ef',
    storageBucket: 'inventory-b52ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-N2YtBd0YcI1CXTDURw-aFeDrmhODfVQ',
    appId: '1:586341334501:ios:b449ec6755f1b24651c30c',
    messagingSenderId: '586341334501',
    projectId: 'inventory-b52ef',
    storageBucket: 'inventory-b52ef.appspot.com',
    iosClientId: '586341334501-snaovkmar8e64j2d40ps0o7jvn039a4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-N2YtBd0YcI1CXTDURw-aFeDrmhODfVQ',
    appId: '1:586341334501:ios:b449ec6755f1b24651c30c',
    messagingSenderId: '586341334501',
    projectId: 'inventory-b52ef',
    storageBucket: 'inventory-b52ef.appspot.com',
    iosClientId: '586341334501-snaovkmar8e64j2d40ps0o7jvn039a4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventory',
  );
}
