name: shared_kernel
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  uuid: ^3.0.7
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.2
